runtime: python311

# This tells Google Cloud how to run your app
# Think of it like instructions for a waiter - "Here's how to serve this dish"

env_variables:
  # Environment variables (like settings for your app)
  GOOGLE_CLOUD_PROJECT: "ai-ml-portfolio-473014"

# Resource limits (to stay within free tier)
automatic_scaling:
  min_instances: 0  # Save money by scaling to zero when not used
  max_instances: 2  # Don't accidentally spend too much
  
instance_class: F1  # Smallest (cheapest) instance type
